DOWN = 0
RIGHT = 1
UP = 2
LEFT = 3
ACTION_LIST = [DOWN, RIGHT, UP, LEFT]
NUM_ACTIONS = len(ACTION_LIST)
NUM_EPOCHS_TD = 500
NUM_EPOCHS_MC = 50000 #NUM_EPOCHS_TD * 1000
NUM_EPOCHS_Q = 5000
NUM_EXP = 10
STEP_SIZE = 0.1
X_AXIS_LOWER_BOUND = -1
X_AXIS_UPPER_BOUND = 1
X_AXIS_RESOLUTION = 100
HORIZON = X_AXIS_RESOLUTION
GRAPH_TYPE = 'plot'
BOARD_SIZE = '5x5'
NUM_OF_STATES = 5*5
DISCOUNT_FACTOR = 1 # FIXME 0.99
EPSILON = 0.5

F_REWARD = 0
G_REWARD = 1
H_REWARD = -1

TRANSITION_FUNCTION = {DOWN: [0.8, 0.1, 0.0, 0.1],
                       RIGHT: [0.1, 0.8, 0.1, 0.0],
                       UP: [0.0, 0.1, 0.8, 0.1],
                       LEFT: [0.1, 0.0, 0.1, 0.8]}

MAPS = {
    "5x5": ["FFSFF",
            "FFFFF",
            "FFFFF",
            "FFFFF",
            "HFFFG"],
    "8x8": [
        "SFFFFFFF",
        "FFHFFHFL",
        "FFFHFFFF",
        "FFFFFHFF",
        "FFFHFFFF",
        "FHHFFFHF",
        "FHTFHFFL",
        "FFFHFFFG",
    ],
    "16x16": [
        "FFFFFFFFSFFFFFFH",
        "FFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFF",
        "FFFFFFFHFFFFFFFF",
        "FFFFFFFFFFFFFFFF",
        "FFHFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFF",
        "FFFFFFFFHFFFFFFF",
        "FFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFF",
        "HFFFFFFFFFFFFFFG"
    ],
    "32x32": [
        "FFFFFFFFSFFFFFFHFFFFFFFFFFFFFFFH",
        "FFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "HFFFFFFFFFFFFFFGHFFFFFFFFFFFFFFG"
    ],
    "128x128": [
        "FFFFFFFFSFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "HFFFFFFFFFFFFFFGHFFFFFFFFFFFFFFGFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFSFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "HFFFFFFFFFFFFFFGHFFFFFFFFFFFFFFGFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFSFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "HFFFFFFFFFFFFFFGHFFFFFFFFFFFFFFGFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFSFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF",
        "HFFFFFFFFFFFFFFGHFFFFFFFFFFFFFFGFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFFFFFFFFFFFHFFFFFF"
    ]
}